name: npm-test

on:
  push:
    branches: [ public ]
  pull_request:
    branches: [ public ]
  workflow_dispatch: # or manual

jobs:

  test:
    runs-on: ubuntu-latest
    steps:

    - name: checkout
      uses: actions/checkout@v2

    - name: install node 14
      uses: actions/setup-node@v3
      with:
        node-version: 14

    - name: install node_modules
      run: npm ci

    - name: run test
      run: npm test
